/*-----------------------------------------------------
 Header for DVBOTC
 for command line options

 This class represents the command
 line for the dvbotc application.
		
 Copyright Damien Morrissey 2007 All rights reserved

 Generated by aargh 1.2
 Fri Aug 17 16:47:33 2007
-----------------------------------------------------*/
#ifndef DVBOTC_OPTS_H_GUARD
#define DVBOTC_OPTS_H_GUARD

struct DVBOTC
{
	int new_argc;
	char ** new_argv;

	char * chan_bw;
	int chan_bw_found;
	char * cell_id;
	int cell_id_found;
	char * debug_output_prefix;
	int debug_output_prefix_found;
	char * guard_interval;
	int guard_interval_found;
	int help;
	char * input_file;
	int input_file_found;
	char * output;
	int output_found;
	char * puncturing_rate;
	int puncturing_rate_found;
	char * qam_level;
	int qam_level_found;
	int no_write;
};

typedef struct DVBOTC DVBOTC;

#ifdef __cplusplus
extern "C" {
#endif

int get_dvbotc_opts( int argc, char * argv[], DVBOTC * pOpts );

/* Declare validator function(s) */

int val_bw( const char * arg );
int val_id( const char * arg );
int val_gi( const char * arg );
int val_pu( const char * arg );
int val_qa( const char * arg );

#ifdef __cplusplus
};
#endif

#endif
